// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qklvmqzpnlzqlbbcuhop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbHZtcXpwbmx6cWxiYmN1aG9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzg2OTAsImV4cCI6MjA1Mzg1NDY5MH0.oxSK1t-QAYqbm1ar1gRusf_PMZ-vBemDz_M1ftyJ5hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);